version: '3.8'

services:
  web:
    build: .
    container_name: flask-app
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - FLASK_DEBUG=1
      - FLASK_ENV=development
    volumes:
      - .:/app
    command: flask run --host=0.0.0.0 --port=5000
  redis:
    image: "redis:alpine"
    container_name: redis-db
    ports:
      - "6379:6379"

